// Opens a Chromium window so you can sign in to Ronspot by hand, and on close leaves you
// the session cookie plus a config.toml already filled in with your GUID, car park and
// vehicle. Your password and the reCAPTCHA token are redacted before anything hits disk.
import { chromium } from 'playwright'
import { appendFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { argv, env } from 'node:process'

const OUT = env.RONSPOT_CAPTURE_DIR ?? argv[2] ?? `${env.HOME}/.ronspot`
mkdirSync(OUT, { recursive: true })
const TRAFFIC = `${OUT}/traffic.jsonl`
const STATE = `${OUT}/session.json`
const CONFIG = `${OUT}/config.toml`

const SECRET = /^(password|pwd|pass|new_?password|confirm_?password|g-recaptcha-response|recaptcha\w*)$/i

function redact(body) {
  if (!body) return null
  if (body.trimStart().startsWith('{')) {
    try {
      const o = JSON.parse(body)
      for (const k of Object.keys(o)) if (SECRET.test(k)) o[k] = '<REDACTED>'
      return JSON.stringify(o)
    } catch { /* fall through to form handling */ }
  }
  return body.split('&').map(kv => {
    const [k, ...v] = kv.split('=')
    return SECRET.test(decodeURIComponent(k)) ? `${k}=<REDACTED>` : `${k}=${v.join('=')}`
  }).join('&')
}

// What the config needs, picked up as you browse.
const found = { guid: null, zone: null, vehicleType: null, vehicleFuel: null, parks: [] }

function learnFromRequest(body) {
  if (!body) return
  const params = new URLSearchParams(body)
  found.guid ??= params.get('CollegesGuID') || params.get('GuId')
  found.zone ??= params.get('car_park_id') || params.get('ZoneID')
}

function learnFromCalendar(payload) {
  const tags = payload?.TagsList
  if (tags?.VehicleType?.length) found.vehicleType ??= tags.VehicleType[0].id
  if (tags?.vehicleFuel?.length) found.vehicleFuel ??= tags.vehicleFuel[0].id
  for (const park of payload?.car_park ?? []) {
    if (!found.parks.some(p => p.id === park.id)) {
      found.parks.push({ id: park.id, name: park.CarParkName })
    }
  }
}

function writeConfig() {
  if (!found.guid || !found.zone) return false
  const others = found.parks
    .filter(p => String(p.id) !== String(found.zone))
    .map(p => `# another car park of yours: zone_id = ${p.id}  # ${p.name}`)
  const chosen = found.parks.find(p => String(p.id) === String(found.zone))
  writeFileSync(CONFIG, `# Generated by tools/capture.mjs. Read it before using it.
[ronspot]
guid = "${found.guid}"
zone_id = ${found.zone}${chosen ? `  # ${chosen.name}` : ''}
vehicle_type_id = ${found.vehicleType ?? 2}
vehicle_fuel_id = ${found.vehicleFuel ?? 2}
${others.join('\n')}${others.length ? '\n' : ''}
[sniper]
weekdays = [1, 3]      # 0 = Monday. [1, 3] = Tuesday and Thursday
horizon_days = 14      # measure yours with --status; mine is 14
giveup_time = "09:30"  # past this the current day is no longer worth chasing
local_tz = "Europe/Madrid"
resync_minutes = 30

[notify]               # console | slack | discord
kind = "console"

[notify.slack]
token = ""
channel = ""

[notify.discord]
webhook = ""

[paths]
session = "${STATE}"
state = "${OUT}/state.json"
`)
  return true
}

const browser = await chromium.launch({ headless: false, args: ['--window-size=1500,980'] })
const ctx = await browser.newContext({ viewport: null })

let n = 0
ctx.on('response', async res => {
  const req = res.request()
  const url = req.url()
  if (!url.includes('ronspot')) return
  const type = req.resourceType()
  if (['image', 'font', 'stylesheet', 'media', 'script'].includes(type)) return
  const ct = res.headers()['content-type'] ?? ''
  let body = null
  if (type !== 'document' && /json|text/.test(ct)) {
    try { body = (await res.text()).slice(0, 6000) } catch { /* body already consumed */ }
  }
  learnFromRequest(req.postData())
  if (body?.trimStart().startsWith('{')) {
    try { learnFromCalendar(JSON.parse(body)) } catch { /* not the calendar */ }
  }
  appendFileSync(TRAFFIC, JSON.stringify({
    i: ++n, t: new Date().toISOString(), method: req.method(), url, type,
    status: res.status(), ct, post: redact(req.postData()), body,
  }) + '\n')
})

const dump = setInterval(async () => {
  try { writeFileSync(STATE, JSON.stringify(await ctx.storageState(), null, 2)) } catch { /* closing */ }
}, 5000)

await (await ctx.newPage()).goto('https://my.ronspot.ie/')
console.log(`
  1. Sign in with your email and password (never stored: it is redacted before any write).
  2. Open your car park calendar and move a week or two forward.
  3. Close the window.

  On close you get, in ${OUT}:
    session.json  the session cookie
    config.toml   your GUID, car park and vehicle, already filled in
`)
await new Promise(resolve => browser.on('disconnected', resolve))
clearInterval(dump)

if (writeConfig()) {
  console.log(`\n  Done. Read ${CONFIG} and set weekdays and giveup_time to taste.`)
} else {
  console.log(`
  I could not find your GUID or car park: did you open the calendar?
  Run it again and browse the calendar before closing the window.`)
}
